# Configuration file for the project

[project]
name = "fyp_cluster"

[controller]
ap_enabled = true
control_port = 8001
data_port = 8002
ethernet_interface = "eth0"
wifi_interface = "wlan0"

[network]
# Default subnets for controller's DHCP server configuration
# Controller will assign IPs in these subnets to workers
# Controller's own IPs will be .1 in each subnet, with CIDR /24 (255.255.255.0)
ethernet_subnet = "192.168.10."
wifi_subnet = "192.168.20."
wifi_ssid = "FYP_Cluster_AP"
wifi_password = "fyp_cluster_pass"

[worker]
control_port = 8001
data_port = 8002
control_interface = "eth0"
ethernet_interface = "eth0"
wifi_interface = "wlan0"